GitHub Actions documentação

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,29 +5,46 @@ on:
     branches: [ "develop", "main" ]
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        node-version: [16.x]
-        
+  test:
+    runs-on: macos-latest
+
     steps:
-      - uses: actions/checkout@v4
-      - name: Create folder for reports
-        run: mkdir reports
-      
-      - name: Run test
-        run: |
-          docker run --shm-size=1g -e BROWSER=headlesschrome \
-          -v ${{github.workspace}}/test:/opt/robotframework/tests:Z \
-          -v ${{github.workspace}}/report:/opt/robotframework/reports:Z \
-          -v ${{github.workspace}}/steps:/opt/robotframework/steps:Z \
-          -v ${{github.workspace}}/template:/opt/robotframework/template:Z \
-          --user 1001:1000 \
-      
-      - name: Publish test results
-        uses: actions/upload-artifact@v4
-        if: always()
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Set up Python
+        uses: actions/setup-python@v4
         with:
-          name: reports
-          path: reports
+          python-version: '3.10'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          # Install additional dependencies if needed
+          pip install -r requirements.txt
+
+      - name: Run Robot Framework tests
+        run: |
+          if ! robot --outputdir report --exclude skip tests/; then
+              echo "Robot Framework tests failed. Rerunning failed tests..."
+              if [ -f report/output.xml ]; then
+                  robot --rerunfailed report/output.xml --outputdir report_rerun tests/ || true
+                  if [ -f report_rerun/output.xml ]; then
+                      rebot --output report/output.xml --log report/log.html --report report/report.html --merge report/output.xml report_rerun/output.xml
+                  else
+                      echo "No output.xml file found from rerun. Skipping merge."
+                  fi
+              else
+                  echo "No output.xml file found. Cannot rerun failed tests."
+              fi
+          fi
+
+          echo "Script execution completed"
+        continue-on-error: true
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          path: ./report
+          name: report
+          
